# Workflow rescrito para utilizar o workflow Reutilizável (Corrigido)
#         uses: Lucas-Pontes-Soares/php-workflows/.github/workflows/login.yml@master

name: CI via Workflow Reutilizável (correção)

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  login:
    uses: Lucas-Pontes-Soares/php-workflows/.github/workflows/login.yml@master